server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  application:
    name: gateway
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      mvc:
        routes:
          - id: user
            uri: http://localhost:8081
            predicates:
              - Path=/api/user/**
            filters:
              - AddRequestHeader=X-Gateway, MyGateway
              - RewritePath=/api/user/(?<segment>.*), /apiv1/user/${segment}
          - id: auth
            uri: http://localhost:8081
            predicates:
              - Path=/api/auth/**
            filters:
              - AddRequestHeader=X-Gateway, MyGateway
              - RewritePath=/api/auth/(?<segment>.*), /apiv1/auth/${segment}
          - id: dashboard
            uri: http://localhost:8083
            predicates:
              - Path=/api/dashboard/**
            filters:
              - AddRequestHeader=X-Gateway, MyGateway
              - RewritePath=/api/dashboard/(?<segment>.*), /apiv1/dashboard/${segment}
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
  data:
    redis:
      host: localhost
      port: 6379
      password:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      default.api.timeout.ms: 5000
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.jdbc.core: TRACE
